{{- if .Values.secretsStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "librecodeinterpreter.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "librecodeinterpreter.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretsStore.provider }}
  parameters:
    {{- if eq .Values.secretsStore.provider "aws" }}
    objects: |
      {{- range .Values.secretsStore.objects }}
      - objectName: {{ .secretArn | quote }}
        objectType: "secretsmanager"
        {{- if .objectAlias }}
        objectAlias: {{ .objectAlias | quote }}
        {{- end }}
        {{- if .jmesPath }}
        jmesPath:
          {{- range .jmesPath }}
          - path: {{ .path | quote }}
            objectAlias: {{ .objectAlias | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- if .Values.secretsStore.secretObjects }}
  secretObjects:
    - secretName: {{ include "librecodeinterpreter.fullname" . }}-aws-secrets
      type: Opaque
      data:
        {{- range .Values.secretsStore.secretObjects }}
        - objectName: {{ .objectName | quote }}
          key: {{ .key | quote }}
        {{- end }}
  {{- end }}
{{- end }}
