apiVersion: v2
name: librecodeinterpreter
description: LibreCodeInterpreter - Kubernetes-native code execution service
type: application
version: 1.0.23
appVersion: "1.0.23"
keywords:
  - code-interpreter
  - code-execution
  - kubernetes
  - python
  - javascript
maintainers:
  - name: Aron Gates
    email: aron@muonspace.com
